### ISSUE TITLE
cv2.error: OpenCV(4.5.5) :-1: error: (-5:Bad argument) in function 'resize'

### ISSUE THREAD

**Issue by blackhat-t** [victorjoh/hard-subs-to-srt#3]
```
Traceback (most recent call last):
  File "/Users/owner/Documents/bins/hard-subs-to-srt/hard_subs_to_srt.py", line 295, in <module>
    main()
  File "/Users/owner/Documents/bins/hard-subs-to-srt/hard_subs_to_srt.py", line 77, in main
    extract_srt(args.video_file, args.srt_file)
  File "/Users/owner/Documents/bins/hard-subs-to-srt/hard_subs_to_srt.py", line 89, in extract_srt
    convert_frames_to_srt(video, FIRST_FRAME)
  File "/Users/owner/Documents/bins/hard-subs-to-srt/hard_subs_to_srt.py", line 130, in convert_frames_to_srt
    cv2.imshow('Orignal', cv2.resize(frame, preview_size))
cv2.error: OpenCV(4.5.5) :-1: error: (-5:Bad argument) in function 'resize'
> Overload resolution failed:
>  - Can't parse 'dsize'. Sequence item with index 0 has a wrong type
>  - Can't parse 'dsize'. Sequence item with index 0 has a wrong type
```

**Comment by kushiwushi** [comment]
Change the PREVIEW_MAX_SIZE value, in my case changing it to a lower number worked
